### ISSUE TITLE
cmake error and make error

### ISSUE THREAD

**Issue by amiltonwong** [afriesen/rdis#3]
Dear all,

I had followed the readme file, after downloading rdis package, I execute cmake .
But came across the error.
The details can be viewed here:
https://goo.gl/DG5nj5

It seems the PaToH library issue.
Then I skip it by "cmake -D USE_PATOH=FALSE ."
It passed.

Then I execute "make"
But came across the following build error.
https://goo.gl/aUqeLA

Any idea or suggestion to fix it?

Thanks in advance~
Milton

**Comment by afriesen** [comment]
It looks like you're using a version of cmake that is between 2.8 and 2.8.11 (see the output of `cmake --version`).

The DIRECTORY command in get_filename_component is only supported after cmake 2.8.11 (see [cmake doc](https://cmake.org/cmake/help/v3.0/command/get_filename_component.html)). If you can upgrade your version of cmake to >= 2.8.11 this should fix the error. Otherwise, you can change DIRECTORY to PATH (see previous doc) and that should fix the error.

**Comment by amiltonwong** [comment]
Thanks @afriesen ,
You're right, my cmake version is old. And after upgrading it into current version 3.4.0, 
The "cmake ." and "make" steps pass. :)
